dataset:
  class_path: part2.dataset.ImageDataset
  args:
    dataset_path: /shared/CS461/cs461_assignment2_data/part2/data/

  collate_fn: part2.models.submission.mil_collate_fn

model:
  class_path: part2.models.submission.Submission
  best_weight_path: ckpts/best_mil.pt

evaluation:
  device: cuda
  batch_size: 16
